site_name: ABRPI Training 2016
site_description: Tutorials for analysing bacterial omics data
site_author: Anna Syme, Torsten Seemann
site_favicon: favicon.ico
theme: yeti
#theme: united
markdown_extensions:
    - admonition
    - smarty
    - tables
    - markdown_include.include
extra_css:
    - css/sepsis.css
pages:
- Home: index.md
- Genomics Workshop:
    - Workshop overview: modules/workshop_overview/index.md
    #- Using Galaxy: modules/galaxy/index.md
    - Starting with Galaxy: modules/galaxy/index.md
    - Training dataset: modules/data-dna/index.md
    #- Quality control: modules/fastqc/index.md
    #- Read trimming: modules/trimmomatic/index.md
    - Genome assembly with Velvet: modules/velvet/index.md
    - Genome assembly with Spades: modules/spades/index.md
    - Genome annotation: modules/prokka/index.md
    - Variant finding: modules/snippy/index.md
    - Public data &rarr; assembly, annotation: modules/access_data/index.md
    - Viral genome sequencing: modules/viral_genomes/index.md


- Genomics:
    - PacBio assembly with SMRT portal: modules/pacbio/index.md
    - PacBio assembly with command line tools: modules/cmdline_assembly/index.md
    #- Annotation using command line tools: modules/cmdline_prokka/index.md
    - Bash scripts: modules/scripts/index.md


- Transcriptomics:
#  - Overview: modules/transcriptomics.md
#  - Dataset: modules/data-rna/index.md
#  #- Quality control: modules/fastqc/index.md
#  #- Read trimming: modules/trimmomatic/index.md
#  - Transcriptome assembly: modules/stringtie/index.md
    - Differential gene expression: modules/dge/index.md
     #- Salmon: modules/salmon/index.md
#- Advanced:
    #- Differential Gene Expression: intro/dge/index.md
    #- Pan genome: intro/roary/index.md
    #- Artemis: modules/artemis/index.md
    #- JBrowse: modules/jbrowse/index.md

- Proteomics:
    - Protein Identification: modules/xtandem/index.md

- Pathway Tools:
    - Pathway annotation and prediction: modules/pathway_tools/annotation/index.md

- About: about/index.md
